In [6]:
import pandas as pd
from meteostat import Stations
import os

In [2]:
stations = Stations()
stations = stations.bounds((50, -110), (30, -65))
stationlist=stations.fetch()

In [5]:
stationlist.groupby(['country','region']).count()

                name  wmo  icao  latitude  longitude  elevation  timezone  \
country region
CA      AB         3    0     3         3          3          3         3
        BC         1    0     1         1          1          1         1
        MB        36   18    14        36         36         36        36
        NB        32   19    18        32         32         32        32
        NS        10    6     5        10         10         10        10
        ON       218   98    99       218        218        218       218
        QC       225   82    85       225        225        225       225
        SK        20   12    10        20         20         20        20
MX      CHH        2    1     2         2          2          2         2
        SON        1    1     0         1          1          1         1
US      AK         1    0     1         1          1          1         1
        AL        48    7    48        48         48         48        48
        AR        38    6    38        38         38         38        38
        AZ         5    1     5         5          5          5         5
        CA         1    0     1         1          1          1         1
        CO        70   12    69        70         70         70        70
        CT        10    2    10        10         10         10        10
        DC         1    1     1         1          1          1         1
        DE         4    1     4         4          4          4         4
        FL        31    9    31        31         31         31        31
        GA        87   15    86        87         87         87        87
        IA        62    8    61        62         62         62        62
        IL        64   15    64        64         64         64        64
        IN        47    6    47        47         47         47        47
        KS        56   11    56        56         56         56        56
        KY        41    7    40        41         41         41        41
        LA        36    7    36        36         36         36        36
        MA        25    9    24        25         25         25        25
        MD        25    6    25        25         25         25        25
        ME        21   10    21        21         21         21        21
        MI        78   17    78        78         78         78        78
        MN       102    6   102       102        102        102       102
        MO        47    9    45        47         47         47        47
        MS        38    8    38        38         38         38        38
        MT        23    4    23        23         23         23        23
        NC        77   16    77        77         77         77        77
        ND        38    4    38        38         38         38        38
        NE        50   12    50        50         50         50        50
        NH        15    6    15        15         15         15        15
        NJ        17    5    17        17         17         17        17
        NM        42   12    41        42         42         42        42
        NY        53   16    52        53         53         53        53
        OH        56    9    56        56         56         56        56
        OK        57   10    57        57         57         57        57
        PA        50    9    50        50         50         50        50
        RI         6    1     6         6          6          6         6
        SC        48    6    48        48         48         48        48
        SD        26    7    25        26         26         26        26
        TN        54    9    53        54         54         54        54
        TX       138   28   138       138        138        138       138
        UT         4    1     4         4          4          4         4
        VA        70    8    70        70         70         70        70
        VT        13    4    13        13         13         13        13
        WI        73    7    73        73         73         73        73
        WV        17    6    17        17         17         17        17
        WY        34   10    34        34         34         34        34

                hourly_start  hourly_end  daily_start  daily_end  \
country region
CA      AB                 2           2            3          3
        BC                 1           1            1          1
        MB                20          20           36         36
        NB                23          23           32         32
        NS                 9           9           10         10
        ON               137         137          212        212
        QC               106         106          216        216
        SK                13          13           20         20
MX      CHH                2           2            0          0
        SON                0           0            1          1
US      AK                 1           1            1          1
        AL                47          47           45         45
        AR                38          38           36         36
        AZ                 5           5            5          5
        CA                 1           1            1          1
        CO                69          69           58         58
        CT                10          10           10         10
        DC                 1           1            1          1
        DE                 4           4            3          3
        FL                31          31           28         28
        GA                86          86           79         79
        IA                61          61           62         62
        IL                64          64           62         62
        IN                47          47           46         46
        KS                56          56           51         51
        KY                40          40           37         37
        LA                35          35           32         32
        MA                24          24           25         25
        MD                24          24           22         22
        ME                19          19           21         21
        MI                77          77           78         78
        MN               102         102           97         97
        MO                45          45           47         47
        MS                38          38           34         34
        MT                23          23           16         16
        NC                75          75           74         74
        ND                38          38           36         36
        NE                48          48           41         41
        NH                14          14           15         15
        NJ                16          16           17         17
        NM                40          40           36         36
        NY                52          52           48         48
        OH                56          56           56         56
        OK                56          56           57         57
        PA                50          50           48         48
        RI                 6           6            6          6
        SC                48          48           47         47
        SD                24          24           24         24
        TN                53          53           49         49
        TX               137         137          134        134
        UT                 3           3            4          4
        VA                70          70           67         67
        VT                11          11           11         11
        WI                73          73           69         69
        WV                17          17           16         16
        WY                34          34           28         28

                monthly_start  monthly_end
country region
CA      AB                  3            3
        BC                  1            1
        MB                 36           36
        NB                 31           31
        NS                  9            9
        ON                203          203
        QC                213          213
        SK                 20           20
MX      CHH                 1            1
        SON                 1            1
US      AK                  1            1
        AL                 43           43
        AR                 33           33
        AZ                  4            4
        CA                  1            1
        CO                 51           51
        CT                 10           10
        DC                  1            1
        DE                  2            2
        FL                 23           23
        GA                 76           76
        IA                 59           59
        IL                 57           57
        IN                 44           44
        KS                 48           48
        KY                 31           31
        LA                 28           28
        MA                 25           25
        MD                 19           19
        ME                 18           18
        MI                 76           76
        MN                 91           91
        MO                 45           45
        MS                 32           32
        MT                 14           14
        NC                 70           70
        ND                 31           31
        NE                 40           40
        NH                 14           14
        NJ                 17           17
        NM                 30           30
        NY                 46           46
        OH                 55           55
        OK                 54           54
        PA                 46           46
        RI                  5            5
        SC                 45           45
        SD                 21           21
        TN                 46           46
        TX                125          125
        UT                  4            4
        VA                 64           64
        VT                 11           11
        WI                 68           68
        WV                 14           14
        WY                 24           24

In [24]:
if not os.path.isdir(r'data/cache'):
    os.makedirs(r'data/cache')

In [39]:
from datetime import datetime
from meteostat import Hourly

Hourly.cache_dir = r'data/cache'

# Set time period
start = datetime(2019, 1, 1)
end = datetime(2022, 8, 31, 23, 59)

# Get hourly data
data = Hourly(stationlist, start, end)
data = data.fetch()
data

Warning: Cannot load hourly/2023/KARB0.csv.gz from https://bulk.meteostat.net/v2/

,temp,dwpt,rhum,prcp,snow,wdir,wspd,wpgt,pres,tsun,coco
time,,,,,,,,,,,
2022-08-31 12:00:00,15.6,13.3,86.0,0.0,NaN,270.0,9.4,NaN,1014.6,NaN,1.0
2022-08-31 13:00:00,18.3,14.4,78.0,0.0,NaN,270.0,14.8,NaN,1014.4,NaN,1.0
2022-08-31 14:00:00,21.7,14.4,63.0,0.0,NaN,280.0,20.5,NaN,1014.2,NaN,1.0
2022-08-31 15:00:00,23.3,15.1,60.0,0.0,NaN,300.0,24.1,NaN,1014.2,NaN,1.0
2022-08-31 16:00:00,25.0,15.0,54.0,0.0,NaN,290.0,25.9,NaN,1014.1,NaN,1.0
2022-08-31 17:00:00,26.1,14.9,50.0,0.0,NaN,260.0,25.9,NaN,1014.0,NaN,1.0
2022-08-31 18:00:00,26.7,14.5,47.0,0.0,NaN,280.0,31.7,NaN,1013.6,NaN,1.0
2022-08-31 19:00:00,27.2,14.6,46.0,0.0,NaN,300.0,25.9,NaN,1013.5,NaN,1.0
2022-08-31 20:00:00,27.2,14.6,46.0,0.0,NaN,290.0,24.1,NaN,1013.0,NaN,2.0
2022-08-31 21:00:00,27.2,14.6,46.0,0.0,NaN,290.0,20.5,NaN,1012.8,NaN,2.0
2022-08-31 22:00:00,26.1,13.2,45.0,0.0,NaN,290.0,20.5,NaN,1012.7,NaN,2.0
2022-08-31 23:00:00,25.6,12.8,45.0,0.0,NaN,290.0,20.5,NaN,1013.0,NaN,1.0

In [40]:
data.to_pickle('data/weatherraw.pkl')