### Clustering to reduce features

In [124]:
import os
import pandas as pd
from datetime import datetime, timedelta
from sklearn.neighbors import KNeighborsClassifier
from sklearn.cluster import KMeans
from sklearn import preprocessing
from sklearn.preprocessing import MinMaxScaler

In [2]:
ROOT_DIR = os.path.realpath(os.path.join(os.getcwd(), '..'))
cln_pkl_loc = os.path.join(ROOT_DIR, 'data','cleanweathersmall.pkl')

In [3]:
df = pd.read_pickle(cln_pkl_loc)
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 3657000 entries, 0 to 3656999
Data columns (total 9 columns):
 #   Column   Dtype
---  ------   -----
 0   station  object
 1   time     datetime64[ns]
 2   temp     float64
 3   dwpt     float64
 4   rhum     float64
 5   prcp     float64
 6   wdir     float64
 7   wspd     float64
 8   pres     float64
dtypes: datetime64[ns](1), float64(7), object(1)
memory usage: 279.0+ MB

### 1. shifting time by 24 hours for Ann Arbor

In [4]:
df_AA=df[df['station']=="KARB0"]

In [5]:
df_AA

,station,time,temp,dwpt,rhum,prcp,wdir,wspd,pres
1310160,KARB0,2022-01-01 00:00:00,5.0,2.9,86.0,0.0,120.0,15.0,1005.0
1310161,KARB0,2022-01-01 01:00:00,5.0,2.9,86.0,0.0,120.0,11.2,1005.4
1310162,KARB0,2022-01-01 02:00:00,5.0,2.9,86.0,0.0,120.0,5.4,1005.3
1310163,KARB0,2022-01-01 03:00:00,5.0,2.9,86.0,0.0,0.0,0.0,1004.9
1310164,KARB0,2022-01-01 04:00:00,5.6,3.3,85.0,0.0,0.0,0.0,1004.9
...,...,...,...,...,...,...,...,...,...
1316515,KARB0,2022-09-22 19:00:00,16.1,2.8,41.0,0.0,329.0,26.6,1017.0
1316516,KARB0,2022-09-22 20:00:00,16.1,2.8,41.0,0.0,328.0,26.3,1017.2
1316517,KARB0,2022-09-22 21:00:00,15.8,2.6,41.0,0.0,329.0,25.2,1017.4
1316518,KARB0,2022-09-22 22:00:00,15.7,2.1,40.0,0.0,332.0,24.8,1017.8
1316519,KARB0,2022-09-22 23:00:00,14.8,2.3,43.0,0.0,334.0,19.8,1018.3

In [29]:
df_NOAA=df[df['station']!="KARB0"]

In [30]:
df_NOAA['time']=df_NOAA['time']+timedelta(hours=24)

C:\Users\paull\AppData\Local\Temp\ipykernel_71516\3671529861.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_NOAA['time']=df_NOAA['time']+timedelta(hours=24)

In [138]:
df_AA

,station,time,temp,dwpt,rhum,prcp,wdir,wspd,pres
1310160,KARB0,2022-01-01 00:00:00,5.0,2.9,86.0,0.0,120.0,15.0,1005.0
1310161,KARB0,2022-01-01 01:00:00,5.0,2.9,86.0,0.0,120.0,11.2,1005.4
1310162,KARB0,2022-01-01 02:00:00,5.0,2.9,86.0,0.0,120.0,5.4,1005.3
1310163,KARB0,2022-01-01 03:00:00,5.0,2.9,86.0,0.0,0.0,0.0,1004.9
1310164,KARB0,2022-01-01 04:00:00,5.6,3.3,85.0,0.0,0.0,0.0,1004.9
...,...,...,...,...,...,...,...,...,...
1316515,KARB0,2022-09-22 19:00:00,16.1,2.8,41.0,0.0,329.0,26.6,1017.0
1316516,KARB0,2022-09-22 20:00:00,16.1,2.8,41.0,0.0,328.0,26.3,1017.2
1316517,KARB0,2022-09-22 21:00:00,15.8,2.6,41.0,0.0,329.0,25.2,1017.4
1316518,KARB0,2022-09-22 22:00:00,15.7,2.1,40.0,0.0,332.0,24.8,1017.8
1316519,KARB0,2022-09-22 23:00:00,14.8,2.3,43.0,0.0,334.0,19.8,1018.3

In [156]:
#removing first day and last day 
#(manual current but could be automated)
df_AA24HR=pd.concat([df_AA,df_NOAA])
df_AA24HR=df_AA24HR[(df_AA24HR['time']>='2022-01-02 00:00:00') & (df_AA24HR['time']<='2022-09-22 23:00:00')]

### 2. Clustering

In [197]:
#Scaling all values for kmeans

scaler = MinMaxScaler()
scaler.fit(df_AA24HR.iloc[:,2:9])
scaled=scaler.fit_transform(df_AA24HR.iloc[:,2:9])
scaled_df=pd.DataFrame(scaled, columns = df.iloc[:2,2:9].columns)
#normalized = preprocessing.normalize(df_AA24HR.iloc[:,2:9])
#normalized
#testknn=df_AA24HR[df_AA24HR['time']=='2022-01-02 1:00:00']
scaled_df=df_AA24HR.iloc[:,0:2].merge(scaled_df, left_index=True, right_index=True)
scaled_df.head()

#testing
scaled_df=scaled_df[scaled_df['time']<='2022-01-30 00:00:00']

In [198]:
#creating a results DF
result_df=pd.DataFrame(scaled_df.station.unique(), columns=['station'])
result_df['total']=0
result_df

    station  total
0     KARB0      0
1     0CNUO      0
2     0CO7B      0
3     0FV1F      0
4     1J1PJ      0
..      ...    ...
568   UJHR7      0
569   UV7W2      0
570   V5792      0
571   VMWBN      0
572   XM44W      0

[573 rows x 2 columns]

In [199]:
#the actual kmeans
knn = KMeans(n_clusters=20)
for t in scaled_df.time.unique():
    dfhour=scaled_df[scaled_df['time']==t].copy()
    knndata=dfhour.iloc[:,2:9]
    knn.fit(knndata)
    y_kmeans = knn.predict(knndata)
    dfhour['cluster']=y_kmeans
    AAcluster=dfhour.loc[dfhour.station=='KARB0','cluster'].values[0]
    df_resulthr=dfhour[dfhour['cluster']==AAcluster].copy()
    df_resulthr['total']=1
    result_df=pd.concat([result_df, df_resulthr[['station','total']]]).groupby(['station']).sum().reset_index()
result_df

    station  total
0     0CNUO      0
1     0CO7B      0
2     0FV1F      0
3     1J1PJ      0
4     1JWST      0
..      ...    ...
568   UJHR7      0
569   UV7W2      0
570   V5792      0
571   VMWBN      0
572   XM44W      0

[573 rows x 2 columns]

In [209]:
station_loc = os.path.join(ROOT_DIR, 'station_analysis','AAstation.csv')
dfstations=pd.read_csv(station_loc)
    #result_df.sort_values(by='total',ascending=False).head(60)
pd.merge(result_df,dfstations,left_on='station', right_on='id').sort_values(by='total',ascending=False).head(60)

,station,total,id,name,country,region,wmo,icao,latitude,longitude,elevation,timezone,hourly_start,hourly_end,daily_start,daily_end,monthly_start,monthly_end,milesfromstat
206,KARB0,673,KARB0,Ann Arbor / Pittsfield,US,MI,NaN,KARB,42.2230,-83.7456,256.0,America/Detroit,2006-01-01,2022-09-22,2006-01-01,2022-04-24,2006-01-01,2022-01-01,0.000000
208,KARV0,229,KARV0,Minocqua / Woodruff,US,WI,NaN,KARV,45.9279,-89.7309,497.0,America/Chicago,2006-01-01,2022-09-22,2006-01-01,2022-04-24,2009-01-01,2022-01-01,392.465081
461,KPDC0,226,KPDC0,Prairie Du Chien / Selchs Mobile Home Park,US,WI,NaN,KPDC,43.0193,-91.1237,201.0,America/Chicago,2006-01-01,2022-09-22,2006-01-01,2022-04-24,2007-01-01,2022-01-01,379.982598
435,KOEB0,223,KOEB0,Coldwater / Countryside Mobile Court,US,MI,NaN,KOEB,41.9336,-85.0523,292.0,America/Detroit,2006-01-01,2022-09-22,2006-01-01,2022-04-25,2008-01-01,2022-01-01,70.093076
209,KASW0,213,KASW0,Warsaw / Monoquet,US,IN,NaN,KASW,41.2747,-85.8401,259.0,America/Indiana/Indianapolis,2006-10-28,2022-09-22,2009-09-05,2022-04-24,2013-01-01,2022-01-01,126.490533
496,KRYM0,209,KRYM0,Ray S Miller Aaf / Camp Ripley Junction,US,MN,NaN,KRYM,46.0912,-94.3605,351.0,America/Chicago,2012-07-13,2022-09-22,2014-02-02,2022-04-24,NaN,NaN,590.699263
229,KBIE0,207,KBIE0,Beatrice / Hoyle North 77 Mobile Homes,US,NE,NaN,KBIE,40.3013,-96.7541,403.0,America/Chicago,2006-01-01,2022-09-22,2006-01-02,2022-04-24,2008-01-01,2022-01-01,689.505441
195,KAHQ0,206,KAHQ0,Wahoo,US,NE,NaN,KAHQ,41.2406,-96.5946,373.0,America/Chicago,2011-05-17,2022-09-22,2011-05-18,2022-04-24,2014-01-01,2022-01-01,667.059311
463,KPEX0,197,KPEX0,Paynesville,US,MN,NaN,KPEX,45.3721,-94.7447,361.0,America/Chicago,2005-08-12,2022-09-22,2005-08-13,2022-04-24,2011-01-01,2022-01-01,590.821951
421,KMPZ0,188,KMPZ0,Mount Pleasant / Woodside Mobile Estates,US,IA,NaN,KMPZ,40.9466,-91.5111,223.0,America/Chicago,2006-01-01,2022-09-22,2006-01-01,2022-04-24,2015-01-01,2022-01-01,411.734003
441,KONL0,183,KONL0,O'neill / Douthit Trailer Court,US,NE,NaN,KONL,42.4695,-98.6873,620.0,America/Chicago,2006-01-01,2022-09-22,2006-01-03,2022-04-24,2007-01-01,2022-01-01,764.231085
481,KRAC0,183,KRAC0,Racine / Ives,US,WI,NaN,KRAC,42.7612,-87.8139,205.0,America/Chicago,2006-01-01,2022-09-22,2006-01-01,2022-04-24,2006-01-01,2022-01-01,211.090905
196,KAIG0,182,KAIG0,Antigo,US,WI,NaN,KAIG,45.1542,-89.1107,464.0,America/Chicago,2006-01-01,2022-09-22,2006-01-01,2022-04-24,2006-01-01,2022-01-01,336.317775
460,KPCZ0,180,KPCZ0,Waupaca,US,WI,NaN,KPCZ,44.3332,-89.0198,256.0,America/Chicago,2006-01-01,2022-09-22,2006-01-04,2022-04-24,2008-01-01,2022-01-01,303.207909
440,KONA0,177,KONA0,Winona / Country Valley Mobile Home Park,US,MN,NaN,KONA,44.0772,-91.7083,200.0,America/Chicago,2006-01-01,2022-09-22,2006-01-01,2022-04-24,2006-01-01,2022-01-01,422.122768
198,KAIT0,176,KAIT0,Aitkin / Welshons Company Mobile Home Park,US,MN,NaN,KAIT,46.5484,-93.6768,368.0,America/Chicago,2006-01-01,2022-09-22,2006-01-01,2022-04-24,2009-01-01,2022-01-01,574.675802
235,KBNW0,176,KBNW0,Boone,US,IA,NaN,KBNW,42.0496,-93.8476,354.0,America/Chicago,2006-01-01,2022-09-22,2006-01-01,2022-04-24,2011-01-01,2022-01-01,518.784900
436,KOEO0,175,KOEO0,Osceola,US,WI,NaN,KOEO,45.3095,-92.6900,276.0,America/Chicago,2006-01-01,2022-09-22,2006-01-01,2022-04-24,2006-01-01,2022-01-01,495.278266
202,KANQ0,174,KANQ0,Angola / Flint,US,IN,NaN,KANQ,41.6397,-85.0835,303.0,America/Indiana/Indianapolis,2020-01-14,2022-09-22,2020-01-14,2022-04-24,2020-01-01,2022-01-01,79.841140
446,KOSH0,174,KOSH0,Oshkosh / Stony Beach,US,WI,NaN,KOSH,43.9844,-88.5570,246.0,America/Chicago,2006-01-01,2022-09-22,2006-01-01,2022-04-24,2006-01-01,2022-01-01,271.992886
429,KMWM0,174,KMWM0,Windom / Bingham Lake,US,MN,NaN,KMWM,43.9134,-95.1094,430.0,America/Chicago,2006-01-01,2022-09-22,2006-01-01,2022-04-24,2007-01-01,2022-01-01,586.347224
212,KATY0,172,KATY0,Watertown,US,SD,NaN,KATY,44.9140,-97.1547,533.0,America/Chicago,1948-01-01,2022-09-22,1948-01-24,2022-04-24,1948-01-01,2022-01-01,697.344181
473,KPOV0,171,KPOV0,Ravenna / Birchwood Manor,US,OH,NaN,KPOV,41.2102,-81.2516,365.0,America/New_York,2009-03-18,2022-09-22,2009-03-19,2022-04-25,2009-01-01,2022-01-01,146.677320
467,KPKD0,170,KPKD0,Park Rapids,US,MN,NaN,KPKD,46.9007,-95.0731,440.0,America/Chicago,1990-01-11,2022-09-22,1995-07-05,2022-04-24,1998-01-01,2022-01-01,644.845504
420,KMOX0,169,KMOX0,Morris,US,MN,NaN,KMOX,45.5660,-95.9672,346.0,America/Chicago,2006-01-01,2022-09-22,2006-01-01,2022-04-24,2006-01-01,2022-01-01,651.540962
497,KRYV0,169,KRYV0,Watertown,US,WI,NaN,KRYV,43.1696,-88.7232,254.0,America/Chicago,2006-01-01,2022-09-22,2006-01-01,2022-04-24,2006-01-01,2022-01-01,261.681498
465,KPHN0,166,KPHN0,Port Huron / Marysville,US,MI,NaN,KPHN,42.9110,-82.5289,198.0,America/Detroit,2006-01-01,2022-09-22,2006-01-01,2022-04-25,2007-01-01,2022-01-01,78.157743
205,KAQP0,166,KAQP0,Appleton,US,MN,NaN,KAQP,45.2275,-96.0043,311.0,America/Chicago,2006-01-01,2022-09-22,2006-01-01,2022-04-24,2007-01-01,2022-01-01,647.081592
232,KBKL0,162,KBKL0,Brookville / Old Chinatown,US,PA,NaN,KBKL,41.5175,-81.6833,178.0,America/New_York,2006-01-01,2022-09-22,2006-01-01,2022-04-24,2006-01-01,2022-01-01,116.993607
425,KMTW0,162,KMTW0,Manitowac / Kellners Corners,US,WI,NaN,KMTW,44.1288,-87.6806,198.0,America/Chicago,2006-01-01,2022-09-22,2006-01-01,2022-04-24,2008-01-01,2022-01-01,238.351636
480,KPZQ0,161,KPZQ0,Presque Isle / Rogers City,US,MI,NaN,KPZQ,45.4071,-83.8129,204.0,America/Detroit,2006-01-01,2022-09-22,2006-01-01,2022-04-25,2006-01-01,2022-01-01,219.855066
469,KPLN0,159,KPLN0,Pellston,US,MI,NaN,KPLN,45.5709,-84.7967,220.0,America/Detroit,1973-01-01,2022-09-22,1973-01-01,2022-04-24,2000-01-01,2021-01-01,237.016818
221,KBAX0,159,KBAX0,Bad Axe,US,MI,NaN,KBAX,43.7802,-82.9854,233.0,America/Detroit,2006-01-01,2022-09-22,2006-01-01,2022-04-24,2008-01-01,2022-01-01,114.183903
495,KRRT0,159,KRRT0,Warroad / Longworth,US,MN,NaN,KRRT,48.9415,-95.3485,328.0,America/Chicago,2006-01-01,2022-09-22,2006-01-01,2022-04-24,2006-01-01,2022-01-01,727.898346
466,KPJC0,158,KPJC0,Zelienople / Old Furnace,US,PA,NaN,KPJC,40.8020,-80.1609,274.0,America/New_York,2020-01-14,2022-09-22,2020-01-14,2022-04-12,2020-01-01,2021-01-01,210.195014
486,KRHI0,156,KRHI0,Rhinelander,US,WI,NaN,KRHI,45.6309,-89.4666,495.0,America/Chicago,2006-01-01,2022-09-22,2006-01-01,2022-04-24,2006-01-01,2022-01-01,369.769549
484,KRDK0,156,KRDK0,Red Oak / Villa Village Mobile Home Park,US,IA,NaN,KRDK,41.0108,-95.2589,319.0,America/Chicago,2006-01-01,2022-09-22,2006-01-01,2022-04-24,2011-01-01,2022-01-01,601.622813
224,KBCK0,155,KBCK0,Black River Falls / Charter Oak Mills (Histori...,US,WI,NaN,KBCK,44.2507,-90.8553,255.0,America/Chicago,2010-11-18,2022-09-22,2010-11-19,2022-04-24,2011-01-01,2022-01-01,385.012354
428,KMWC0,155,KMWC0,Milwaukee / Butler,US,WI,NaN,KMWC,43.1104,-88.0344,227.0,America/Chicago,1973-01-01,2022-09-22,2020-01-14,2022-04-24,2020-01-01,2022-01-01,226.866773
238,KBTL0,155,KBTL0,Battle Creek / Avenue A Mobile Home Estates,US,MI,NaN,KBTL,42.3073,-85.2515,290.0,America/Detroit,1942-10-01,2022-09-22,1942-11-02,2022-04-24,1942-01-01,2022-01-01,77.420603
475,KPQN0,155,KPQN0,Pipestone,US,MN,NaN,KPQN,43.9833,-96.3003,529.0,America/Chicago,2006-01-01,2022-08-02,2006-01-01,2022-04-24,2012-01-01,2022-01-01,645.894729
182,K4R50,154,K4R50,La Pointe,US,WI,NaN,K4R5,46.7887,-90.7587,198.0,America/Chicago,2016-11-11,2022-09-21,2016-11-12,2022-03-08,NaN,NaN,468.133034
215,KAWG0,154,KAWG0,Washington,US,IA,NaN,KAWG,41.2750,-91.6752,230.0,America/Chicago,2006-01-01,2022-09-22,2006-01-01,2022-04-24,2014-01-01,2022-01-01,414.855204
431,KMZH0,154,KMZH0,Moose Lake,US,MN,NaN,KMZH,46.4186,-92.8048,328.0,America/Chicago,2006-01-01,2022-09-22,2006-01-01,2022-04-24,2006-01-01,2022-01-01,533.865683
474,KPPO0,153,KPPO0,La Porte / South Laporte,US,IN,NaN,KPPO,41.5725,-86.7345,248.0,America/Chicago,2012-04-02,2022-09-22,2012-04-03,2022-04-24,2015-01-01,2022-01-01,160.513636
200,KAMN0,153,KAMN0,Alma / Eugene,US,MI,NaN,KAMN,43.3221,-84.6879,230.0,America/Detroit,2006-01-01,2022-09-22,2006-01-01,2022-04-24,2006-01-01,2022-01-01,89.732372
220,KBAC0,152,KBAC0,Valley City / North Valley City,US,ND,NaN,KBAC,46.9412,-98.0180,427.0,America/Chicago,2010-12-15,2022-09-22,2010-12-16,2022-04-24,2014-01-01,2022-01-01,774.487028
504,KSGS0,152,KSGS0,Saint Paul / Inver Grove Heights,US,MN,NaN,KSGS,44.8571,-93.0329,250.0,America/Chicago,2006-01-01,2022-09-22,2006-01-01,2022-04-24,2006-01-01,2022-01-01,500.247373
450,KOVL0,151,KOVL0,Olivia,US,MN,NaN,KOVL,44.7786,-95.0328,328.0,America/Chicago,2006-01-01,2022-09-22,2006-01-01,2022-04-24,2006-01-01,2022-01-01,593.446621
439,KOLZ0,151,KOLZ0,Oelwein,US,IA,NaN,KOLZ,42.6808,-91.9745,328.0,America/Chicago,2006-01-01,2022-09-22,2006-01-05,2022-04-24,2012-01-01,2022-01-01,421.639014
472,KPNT0,150,KPNT0,Pontiac / Cayuga,US,IL,NaN,KPNT,40.9244,-88.6239,203.0,America/Chicago,2006-09-26,2022-09-22,2011-03-18,2022-04-24,2015-01-01,2022-01-01,268.175428
452,KOWA0,150,KOWA0,Owatonna / Clinton Falls,US,MN,NaN,KOWA,44.1230,-93.2588,349.0,America/Chicago,2006-01-01,2022-09-22,2006-01-01,2022-04-24,2006-01-01,2022-01-01,497.899896
488,KRNH0,149,KRNH0,New Richmond / Woodbridge Trailer Court,US,WI,NaN,KRNH,45.1478,-92.5392,304.0,America/Chicago,2006-01-01,2022-09-22,2006-01-02,2022-04-24,2007-01-01,2022-01-01,484.281723
203,KANW0,146,KANW0,Ainsworth / Sandridge,US,NE,NaN,KANW,42.5792,-99.9930,789.0,America/Chicago,2006-01-01,2022-09-22,2006-01-01,2022-04-24,2007-01-01,2022-01-01,830.248483
194,KAFK0,146,KAFK0,Nebraska City / Paul,US,NE,NaN,KAFK,40.6054,-95.8678,355.0,America/Chicago,2006-01-01,2022-09-22,2006-01-01,2022-04-24,2007-01-01,2022-01-01,638.996219
459,KPCW0,146,KPCW0,Port Clinton / Gypsum,US,OH,NaN,KPCW,41.5163,-82.8695,180.0,America/New_York,2014-07-31,2022-09-22,2014-08-01,2022-04-25,2020-01-01,2022-01-01,66.492955
210,KASX0,146,KASX0,Ashland / Ashland Junction,US,WI,NaN,KASX,46.5485,-90.9190,252.0,America/Chicago,2006-01-01,2022-09-22,2006-01-01,2022-04-24,2006-01-01,2022-01-01,463.723705
483,KRCX0,145,KRCX0,Ladysmith / Tony,US,WI,NaN,KRCX,45.4968,-91.0005,378.0,America/Chicago,2009-06-17,2022-09-22,2009-06-17,2022-04-24,2009-01-01,2022-01-01,426.865846
213,KAUH0,145,KAUH0,Aurora,US,NE,NaN,KAUH,40.8941,-97.9946,550.0,America/Chicago,2006-01-01,2022-09-22,2006-01-01,2022-04-24,2007-01-01,2022-01-01,743.384811
438,KOLG0,143,KOLG0,Solon Springs,US,WI,NaN,KOLG,46.3148,-91.8164,336.0,America/Chicago,2020-01-14,2022-09-22,2020-01-14,2022-04-24,2020-01-01,2022-01-01,489.645915

In [54]:
testknn['cluster']=y_kmeans

C:\Users\paull\AppData\Local\Temp\ipykernel_71516\671720110.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  testknn['cluster']=y_kmeans

In [56]:
testknn[testknn['cluster']==14]

,station,time,temp,dwpt,rhum,prcp,wdir,wspd,pres,cluster
1310185,KARB0,2022-01-02 01:00:00,-2.8,-5.6,81.0,0.7,30.0,16.6,1010.2,14
184441,71352,2022-01-02 01:00:00,1.7,0.2,90.0,0.0,40.0,7.0,1010.1,14
591481,72530,2022-01-02 01:00:00,5.0,3.3,89.0,0.0,40.0,18.4,1004.0,14
648721,72539,2022-01-02 01:00:00,3.9,0.1,76.0,0.0,50.0,11.2,1005.6,14
763201,72635,2022-01-02 01:00:00,1.7,0.5,92.0,0.0,40.0,14.8,1006.4,14
769561,72636,2022-01-02 01:00:00,2.2,-0.6,82.0,0.0,40.0,13.0,1006.2,14
782281,72638,2022-01-02 01:00:00,0.0,-2.9,81.0,0.0,50.0,9.4,1008.1,14
795001,72640,2022-01-02 01:00:00,3.3,1.2,86.0,0.3,30.0,18.4,1006.0,14
807721,72642,2022-01-02 01:00:00,-1.7,-3.9,85.0,0.0,30.0,14.8,1007.2,14
1252921,KAIO0,2022-01-02 01:00:00,-6.0,-6.0,100.0,0.0,40.0,20.5,1011.0,14
1392841,KAZO0,2022-01-02 01:00:00,6.7,3.8,82.0,0.0,40.0,5.4,1004.9,14
1570921,KCAD0,2022-01-02 01:00:00,0.1,-2.1,85.0,0.0,30.0,9.4,1005.0,14
1653601,KCLI0,2022-01-02 01:00:00,-2.0,-5.0,80.0,0.0,30.0,5.4,1010.0,14
1895281,KENW0,2022-01-02 01:00:00,3.3,1.7,89.0,0.3,40.0,13.0,1005.3,14
1914361,KETB0,2022-01-02 01:00:00,-2.0,-2.0,100.0,0.0,50.0,14.8,1007.0,14
2124241,KGOV0,2022-01-02 01:00:00,-0.9,-2.2,91.0,0.0,50.0,7.6,1008.7,14
2435881,KLDM0,2022-01-02 01:00:00,0.8,-2.6,78.0,0.0,30.0,7.6,1007.0,14
2467681,KLOT0,2022-01-02 01:00:00,5.5,5.5,100.0,0.0,40.0,11.2,1004.0,14
2537641,KMBS0,2022-01-02 01:00:00,1.7,-0.6,85.0,0.0,30.0,14.8,1007.3,14
2594881,KMGN0,2022-01-02 01:00:00,-0.7,-3.6,81.0,0.0,30.0,7.6,1008.0,14
2652121,KMNM0,2022-01-02 01:00:00,-2.8,-4.4,89.0,0.1,40.0,7.6,1009.8,14
3059161,KRAC0,2022-01-02 01:00:00,3.3,2.3,93.0,0.0,40.0,16.6,1006.1,14
3262681,KSUE0,2022-01-02 01:00:00,-2.2,-5.0,81.0,0.2,50.0,7.6,1009.2,14
3370801,KUGN0,2022-01-02 01:00:00,3.9,2.9,93.0,0.1,40.0,16.6,1005.2,14
3472561,KY310,2022-01-02 01:00:00,0.0,-1.8,88.0,0.0,40.0,11.0,1006.0,14

In [116]:
testknn2=df_AA24HR[df_AA24HR['time']=='2022-01-15 8:00:00']

In [117]:
testdata=testknn2.iloc[:,2:9]
knn = KMeans(n_clusters=20)
knn.fit(testdata)
y_kmeans = knn.predict(testdata)
testknn2['cluster']=y_kmeans
AAcluster=testknn2.loc[testknn2.station=='KARB0','cluster'].values[0]

C:\Users\paull\AppData\Local\Temp\ipykernel_71516\2352707111.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  testknn2['cluster']=y_kmeans

6

In [118]:
supertest=testknn2[testknn2['cluster']==AAcluster].merge(testknn[testknn['cluster']==14], left_on='station', right_on='station')

In [119]:
supertest

,station,time_x,temp_x,dwpt_x,rhum_x,prcp_x,wdir_x,wspd_x,pres_x,cluster_x,time_y,temp_y,dwpt_y,rhum_y,prcp_y,wdir_y,wspd_y,pres_y,cluster_y
0,KARB0,2022-01-15 08:00:00,-11.1,-15.7,69.0,0.0,50.0,20.5,1028.5,19,2022-01-02 01:00:00,-2.8,-5.6,81.0,0.7,30.0,16.6,1010.2,14
1,KCLI0,2022-01-15 08:00:00,-8.0,-13.1,67.0,0.0,50.0,18.4,1023.0,19,2022-01-02 01:00:00,-2.0,-5.0,80.0,0.0,30.0,5.4,1010.0,14
2,KGOV0,2022-01-15 08:00:00,-9.0,-12.0,79.0,0.0,50.0,22.3,1022.2,19,2022-01-02 01:00:00,-0.9,-2.2,91.0,0.0,50.0,7.6,1008.7,14
3,KLDM0,2022-01-15 08:00:00,-4.7,-10.7,63.0,0.0,50.0,11.2,1021.0,19,2022-01-02 01:00:00,0.8,-2.6,78.0,0.0,30.0,7.6,1007.0,14